### PR TITLE
use serial builder

### PR DESCRIPTION
**Pull request by ktbartholomew**

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-50eee23954/docs/cloud-images/v2/developer-guide/)

**Comment by catlook** [comment]
Hmmm…clicking on sidebar entries gets page not found :(

-- Cat Lookabaugh, Sr. Information Developer
Rackspace Hosting – the #1 Managed Cloud Company
DevDocs on Developer Experience Team
Office: (210) 312-8193   Cell: (210) 364-1060
cat.lookabaugh@rackspace.com

We should not write so that it is possible for the reader to understand us, but so that it is impossible for him to misunderstand us. - Quintilian, rhetorician (c. 35-100)

Harmony + Learner + Responsibility + Context + Intellection + Arranger + Consistency + Relator + Input + Analytical

**Comment by ktbartholomew** [comment]
@catlook Yeah I'm seeing that on a couple of links, but not all of them...

**Comment by kmsholcomb** [comment]
Seems to be just the getting started section. Is it weird that the URL for those topics contain "quickstart" in it? I don't think we use that in the URL for any of the API docs. Maybe that's the issue?

**Comment by ktbartholomew** [comment]
https://github.com/rackerlabs/nexus-control/issues/457

**Pull request merged**
